formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: ["resources", "data-sources", "modules"]
  show: []

content: |-

  # Terraform Digitalocean Droplet

  This Terraform module creates an opinionated Droplet on Digitalocean for Cosmos Blockchain Nodes.

  ## Usage Examples

  Some examples can be found in this repository:

  - [Simple Droplet](./examples/simple-droplet)
  - [Droplet with Volume](./examples/droplet-with-volume)
  - [Droplet with Floating IP](./examples/droplet-with-floating-ip)
  - [Droplet with Monitor Alert](./examples/droplet-with-monitor-alert)


  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}  

  {{ .Outputs }}

  ## Usage

  ```hcl
  {{ include "examples/simple-droplet/main.tf" }}
  ```

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: false
