#cloud-config
groups:
  - docker

users:
  - name: ${username}
    groups: 
      - sudo
      - docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_authorized_key}

package_update: true
package_upgrade: false
packages:
  - liblz4-tool 
  - aria2 
  - make

runcmd:
  - sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
  - service ssh reload
  - chown ${username}:${username} -R /home/${username}/
